### ISSUE TITLE
xdebug-toggle off : Xdebug for PHP 5.6 was never installed 

### ISSUE THREAD

**Issue by justinlevi** [w00fz/xdebug-osx#11]
[UPDATE: I FIXED THE GLITCH...]

I recently downgraded to OSX 10.12.3 (Sierra) from the Beta build releases and needed to reinstall my local LAMP stack. Everything seems to be running fine except xdebug-toggle which I was relying on heavily because it's super useful!

When I run the command, I get the following message: 

```
Xdebug for PHP 5.6 was never installed or not installed via Brew.
For more informations: http://github.com/w00fz/xdebug-osx/blob/master/README.md
```

I've got php56 installed as well as php56-xdebug. I did a $ `brew reinstall` on all of my php versions as well as `httpd24`.

![screen shot 2017-02-09 at 11 54 15 am](https://cloud.githubusercontent.com/assets/1117989/22793677/82f33aa0-eebe-11e6-94e3-218fcfb86737.jpg)

I can see the ext-xdebug.ini file here as well. 

`/usr/local/etc/php/5.6/conf.d/ext-xdebug.ini`

I've been trying to understand the shell script to see what might be the issue here but running into a few road blocks. 

Here are the values of each variable set in the script: 

```
⚡ echo $php_version_dot
5.6

⚡ echo $php_version
56

⚡ echo $xdebug_conf_path
/usr/local/etc/php/5.6/conf.d

⚡ echo $xdebug_conf_file
ext-xdebug.ini

⚡ echo $xdebug_conf
/usr/local/etc/php/5.6/conf.d/ext-xdebug.ini

⚡ brew list php$php_version-xdebug
/usr/local/Cellar/php56-xdebug/2.5.0/xdebug.so

```

So then if I understand correctly, these next two lines are saying: 

```
brew list php$php_version-xdebug 2> /dev/null > /dev/null
if [ $? -eq 0 ]; then
```

Running the `brew list php56-xdebug` command should return a result.
You are sending the standard error output to /dev/null, which is essentially ignoring it, right? 
So if the command equals 0 means that it's a success...

If I run the command manually I get "SUCCESS"???

```

⚡ brew list php$php_version-xdebug 2> /dev/null > /dev/null
justinwinter in ~/Sites/wny [-b develop*]
⚡ if [ $? -eq 0 ]; then
→ echo SUCCESS
→ else
→ echo FAILURE
→ fi
SUCCESS

```

LOL - I just copied and pasted the entire shell script into the terminal and got the following message back:

```
xdebug-toggle on
Xdebug has been enabled, restarting php-fpm
You are running PHP v5.6 with Xdebug enabled
```

I then had the bright idea of restarting my shell... leaving this mess of a question here because I spent way too long writing it up and I don't want to delete it... :)

**Comment by w00fz** [comment]
Hah no problem, glad you sorted anyway!
Still not quite sure why that was, perhaps you just needed to `source` your shell profile after the reinstall.

I'm assuming you are all up and running again with `xdebug-toggle` now, can this be closed now?

**Comment by justinlevi** [comment]
Yes, all set. I'll close. 

Thanks again for a super useful shell script.
