### ISSUE TITLE
wrong check for extension path

### ISSUE THREAD

**Issue by sp-daniel-pinyol** [w00fz/xdebug-osx#17]
Hi,
I think the're a type on the script
On https://github.com/w00fz/xdebug-osx/blob/master/xdebug-toggle#L19 it says
`if [ ! -f "extension_dir"/xdebug.so ]; then`
where it should say
`if [ ! -f "$extension_dir"/xdebug.so ]; then`

right?

**Comment by w00fz** [comment]
Thanks, fixed!
