### ISSUE TITLE
nginx support

### ISSUE THREAD

**Issue by endelwar** [w00fz/xdebug-osx#5]
Actually only Apache is supported.
On nginx setup usually `php-fpm` is used, so a restart of `php-fpm` should be done in this case.

**Comment by w00fz** [comment]
Is restart the only issue with this?

**Comment by endelwar** [comment]
on cli application xdebug is disabled/enabled correctly, but php-fpm needs a manual restart to see xdebug status

**Comment by w00fz** [comment]
Because I never used nginx on my local via homebrew, can you tell if something like this would do the trick, assuming you are using PHP 5.6

``` bash
$ launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.php56.plist
$ launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php56.plist
```

**Comment by endelwar** [comment]
yes, this is the standard way to reload php-fpm and it works flawlessly; lately I've tapped `homebrew/services` so I use `brew services restart php56` to restart it

**Comment by w00fz** [comment]
hey @endelwar, can you give it a shot now with my latest change? That should take care of restarting php-fpm for you.

Thanks!

**Comment by endelwar** [comment]
Thanks @w00fz, it's working perfectly!
Just a quick note: the output says that `nginx` is restarting, but it's `php-fpm` that it's actually restarting.

**Comment by w00fz** [comment]
You are totally right! I'll fix the echo, thanks!
