### ISSUE TITLE
Ability to optionally disable Apache and PHP-FPM restart

### ISSUE THREAD

**Issue by exequiel09** [w00fz/xdebug-osx#6]
I find this script really useful. But sometimes, IMO, a server restart is not really needed especially when you're using Composer with Xdebug. Composer throws some warning if it detects that Xdebug is installed. Currently, i am using this solution [Running Composer without Xdebug](https://stackoverflow.com/questions/38506140/how-to-run-composer-without-xdebug-when-installed-with-homebrew#answer-38506141).

Sample logic in my [forked repository](https://github.com/exequiel09/xdebug-osx/blob/c028e5bd667f1c43ae6b9888373c0311f46b7238/xdebug-toggle#L59)

**Comment by w00fz** [comment]
I like this a lot!
Would you mind making a PR for it?

**Comment by exequiel09** [comment]
Will do @w00fz. Will just test some things out and will send PR immediately after.

**Comment by exequiel09** [comment]
Already sent pull request #8 . Thanks

**Comment by w00fz** [comment]
Merged, thanks.
