### ISSUE TITLE
Set XDebug Off by default? 

### ISSUE THREAD

**Issue by justinlevi** [w00fz/xdebug-osx#9]
Huge fan of this little helper command! Thanks for the great work and for sharing!

I'd like to disable xdebug by default and wondering what the best way to go about doing that in a way that doesn't conflict with this. The issue is mainly that xdebug causes a composer performance hit so having it off on restart is preferable.

**Comment by w00fz** [comment]
Hi!
the best way to disable manually xdebug by default while keeping the `xdebug-toggle` functionality available is by renaming the extension to `ext-xdebug.ini.disabled`:

`/usr/local/etc/php/7.0/conf.d/ext-xdebug.ini.disabled`

This will be detected by both the toggle and php.

Hope this is what you were looking for.

**Comment by geekish** [comment]
Re: Composer performance, it looks like they may have [found a solution](https://github.com/composer/composer/pull/5580).
